### ISSUE TITLE
Laravel5 could not be found and loaded

### ISSUE THREAD

**Issue by ajtrichards** [janhenkgerritsen/codeception-laravel5#6]
I've followed the install instructions for this package and run `codecept build` and i'm getting an error:

```bash
codecept build
Building Actor classes for suites: acceptance, functional, unit


                                          
  [Codeception\Exception\Configuration]   
  Laravel5 could not be found and loaded  
                                          


build [-c|--config[="..."]]

```

My composer file is as follows, and I didn't have any errors after running `composer update`

```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "~5.0",
		"illuminate/html": "5.0.*@dev"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
                "codeception/codeception": "~2.0",
                "janhenkgerritsen/codeception-laravel5": "dev-master",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "dev"
}
```

Have I missed out a step somewhere?

**Comment by abstractFlo** [comment]
have you try composer update --dev ?

**Comment by ajtrichards** [comment]
yeah i've run that command too - still the same response.

**Comment by janhenkgerritsen** [comment]
Do you have Codeception installed globally? If Codeception is installed globally and my package only locally, the global composer installation cannot find the classes in my package, and you will get this error.

**Comment by ajtrichards** [comment]
Ah yes - i've made Codeception available globally rather than just use the .phar file.

Will try that out now and let you know

**Comment by ajtrichards** [comment]
I've deleted the global install of Codeception and used the `codeception.phar` file and i still get the same response.

**Comment by janhenkgerritsen** [comment]
You should not use the phar file, but the codeception executable in the `./vendor/bin` directory. You have to use this one because this file will use the composer autoloader, from which my package will be available. It will not be available in the phar file or a global installation of Codeception.

When there is a stable release of Laravel 5 I can send a pull request to include my Laravel 5 module into the Codeception package, and then all these problems will be solved. But untill then you should use the `./vendor/bin/codeception` executable for your tests.

**Comment by ajtrichards** [comment]
Ah right - got it. It's working now.

Sorry about that!
