### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!  with Queues

### ISSUE THREAD

**Issue by bcdennis** [janhenkgerritsen/codeception-laravel5#8]
FATAL ERROR. TESTS NOT FINISHED.
Maximum function nesting level of '100' reached, aborting!

This occurs whenever a functional test is run that covers anything that uses the Queue. 

This appears to also be occurring in the L4 module too.
https://laracasts.com/discuss/channels/general-discussion/larabook-ch-27-functional-test-signupcept-fatal-error

**Comment by janhenkgerritsen** [comment]
In (this issue)[https://github.com/janhenkgerritsen/codeception-laravel5/issues/1] the same error was thrown, and the solution was to increase the value of the `xdebug.max_nesting_level` setting in the php.ini file. Could you try that?

**Comment by bcdennis** [comment]
I saw that and that does work, my concern is that I'm not sure I'll be able to do that on Travis.

**Comment by janhenkgerritsen** [comment]
I don't know if Xdebug is installed by default in Travis, but if so you can specify custom PHP configuration settings like this: http://docs.travis-ci.com/user/languages/php/#Custom-PHP-configuration

**Comment by bcdennis** [comment]
Yes, thank you.
